db:
    build: mysql/.
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw

web:
    build: webapp/.
    ports:
     - "8080:80"
    links:
     - db
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
