ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name docker_omegaup_grader_1 -name docker_omegaup_runner_1 -name docker_omegaup_frontend_1"

omegaup_db:
  build: mysql/.
  ports:
    - "3306:3306"
  volumes:
    - ./volumes/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw

omegaup_frontend:
  build: frontend/.
  ports:
    - "8080:80"
  links:
    - omegaup_db
    - "ambassador:omegaup_grader"
  volumes:
    - ./volumes/log/omegaup/frontend:/var/log/omegaup
    - ./volumes/log/nginx:/var/log/nginx
    - ./volumes/log/hhvm:/var/log/hhvm
    - ./volumes/lib/omegaup:/var/lib/omegaup
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw

omegaup_grader:
  build: grader/.
  ports:
    - "21680:21680"
  links:
    - omegaup_db
    - "ambassador:omegaup_runner"
    - "ambassador:omegaup_frontend"
  volumes:
    - ./volumes/log/omegaup/grader:/var/log/omegaup
    - ./volumes/lib/omegaup:/var/lib/omegaup
  environment:
    - MYSQL_ROOT_PASSWORD=my-secret-pw

omegaup_runner:
  build: runner/.
  ports:
    - "21681:21681"
  links:
    - "ambassador:omegaup_grader"
  volumes:
    - ./volumes/log/omegaup/runner:/var/log/omegaup
