omegaup_db:
    build: mysql/.
    ports:
     - "3306:3306"
    volumes:
     - ./volumes/lib/mysql:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw

omegaup_frontend:
    build: frontend/.
    ports:
     - "8080:80"
    links:
     - omegaup_db
    volumes:
     - ./volumes/log/omegaup:/var/log/omegaup
     - ./volumes/log/nginx:/var/log/nginx
     - ./volumes/log/hhvm:/var/log/hhvm
     - ./volumes/log/omegaup:/var/log/omegaup
     - ./volumes/lib/omegaup:/var/lib/omegaup
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
